apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
      - name: backend
        image: gcr.io/nginsako/web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND_ENDPOINT_URL
            value: "http://backend.nginx-mra.svc.cluster.local:8080"
---
